package net.jradius.dal.model;

import com.coova.dal.Record;
import java.util.Date;

public class RadAcct extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctsessionid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String acctsessionid = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctuniqueid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String acctuniqueid = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String username = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.groupname
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String groupname = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.realm
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String realm = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.nasipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String nasipaddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.nasportid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String nasportid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.nasporttype
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String nasporttype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctstarttime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Date acctstarttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctstoptime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Date acctstoptime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctsessiontime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Integer acctsessiontime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctauthentic
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String acctauthentic;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.connectinfo_start
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String connectinfoStart;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.connectinfo_stop
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String connectinfoStop;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctinputoctets
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Long acctinputoctets;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctoutputoctets
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Long acctoutputoctets;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.calledstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String calledstationid = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.callingstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String callingstationid = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctterminatecause
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String acctterminatecause = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.servicetype
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String servicetype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.framedprotocol
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String framedprotocol;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.framedipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String framedipaddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctstartdelay
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Integer acctstartdelay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.acctstopdelay
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Integer acctstopdelay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radacct.xascendsessionsvrkey
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String xascendsessionsvrkey;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.id
     *
     * @return the value of radacct.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.id
     *
     * @param id the value for radacct.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctsessionid
     *
     * @return the value of radacct.acctsessionid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getAcctsessionid() {
        return acctsessionid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctsessionid
     *
     * @param acctsessionid the value for radacct.acctsessionid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctsessionid(String acctsessionid) {
        this.acctsessionid = acctsessionid == null ? null : acctsessionid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctuniqueid
     *
     * @return the value of radacct.acctuniqueid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getAcctuniqueid() {
        return acctuniqueid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctuniqueid
     *
     * @param acctuniqueid the value for radacct.acctuniqueid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctuniqueid(String acctuniqueid) {
        this.acctuniqueid = acctuniqueid == null ? null : acctuniqueid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.username
     *
     * @return the value of radacct.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.username
     *
     * @param username the value for radacct.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.groupname
     *
     * @return the value of radacct.groupname
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.groupname
     *
     * @param groupname the value for radacct.groupname
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.realm
     *
     * @return the value of radacct.realm
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getRealm() {
        return realm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.realm
     *
     * @param realm the value for radacct.realm
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setRealm(String realm) {
        this.realm = realm == null ? null : realm.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.nasipaddress
     *
     * @return the value of radacct.nasipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getNasipaddress() {
        return nasipaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.nasipaddress
     *
     * @param nasipaddress the value for radacct.nasipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setNasipaddress(String nasipaddress) {
        this.nasipaddress = nasipaddress == null ? null : nasipaddress.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.nasportid
     *
     * @return the value of radacct.nasportid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getNasportid() {
        return nasportid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.nasportid
     *
     * @param nasportid the value for radacct.nasportid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setNasportid(String nasportid) {
        this.nasportid = nasportid == null ? null : nasportid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.nasporttype
     *
     * @return the value of radacct.nasporttype
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getNasporttype() {
        return nasporttype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.nasporttype
     *
     * @param nasporttype the value for radacct.nasporttype
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setNasporttype(String nasporttype) {
        this.nasporttype = nasporttype == null ? null : nasporttype.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctstarttime
     *
     * @return the value of radacct.acctstarttime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Date getAcctstarttime() {
        return acctstarttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctstarttime
     *
     * @param acctstarttime the value for radacct.acctstarttime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctstarttime(Date acctstarttime) {
        this.acctstarttime = acctstarttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctstoptime
     *
     * @return the value of radacct.acctstoptime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Date getAcctstoptime() {
        return acctstoptime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctstoptime
     *
     * @param acctstoptime the value for radacct.acctstoptime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctstoptime(Date acctstoptime) {
        this.acctstoptime = acctstoptime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctsessiontime
     *
     * @return the value of radacct.acctsessiontime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Integer getAcctsessiontime() {
        return acctsessiontime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctsessiontime
     *
     * @param acctsessiontime the value for radacct.acctsessiontime
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctsessiontime(Integer acctsessiontime) {
        this.acctsessiontime = acctsessiontime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctauthentic
     *
     * @return the value of radacct.acctauthentic
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getAcctauthentic() {
        return acctauthentic;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctauthentic
     *
     * @param acctauthentic the value for radacct.acctauthentic
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctauthentic(String acctauthentic) {
        this.acctauthentic = acctauthentic == null ? null : acctauthentic.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.connectinfo_start
     *
     * @return the value of radacct.connectinfo_start
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getConnectinfoStart() {
        return connectinfoStart;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.connectinfo_start
     *
     * @param connectinfoStart the value for radacct.connectinfo_start
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setConnectinfoStart(String connectinfoStart) {
        this.connectinfoStart = connectinfoStart == null ? null : connectinfoStart.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.connectinfo_stop
     *
     * @return the value of radacct.connectinfo_stop
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getConnectinfoStop() {
        return connectinfoStop;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.connectinfo_stop
     *
     * @param connectinfoStop the value for radacct.connectinfo_stop
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setConnectinfoStop(String connectinfoStop) {
        this.connectinfoStop = connectinfoStop == null ? null : connectinfoStop.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctinputoctets
     *
     * @return the value of radacct.acctinputoctets
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long getAcctinputoctets() {
        return acctinputoctets;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctinputoctets
     *
     * @param acctinputoctets the value for radacct.acctinputoctets
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctinputoctets(Long acctinputoctets) {
        this.acctinputoctets = acctinputoctets;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctoutputoctets
     *
     * @return the value of radacct.acctoutputoctets
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long getAcctoutputoctets() {
        return acctoutputoctets;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctoutputoctets
     *
     * @param acctoutputoctets the value for radacct.acctoutputoctets
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctoutputoctets(Long acctoutputoctets) {
        this.acctoutputoctets = acctoutputoctets;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.calledstationid
     *
     * @return the value of radacct.calledstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getCalledstationid() {
        return calledstationid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.calledstationid
     *
     * @param calledstationid the value for radacct.calledstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setCalledstationid(String calledstationid) {
        this.calledstationid = calledstationid == null ? null : calledstationid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.callingstationid
     *
     * @return the value of radacct.callingstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getCallingstationid() {
        return callingstationid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.callingstationid
     *
     * @param callingstationid the value for radacct.callingstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setCallingstationid(String callingstationid) {
        this.callingstationid = callingstationid == null ? null : callingstationid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctterminatecause
     *
     * @return the value of radacct.acctterminatecause
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getAcctterminatecause() {
        return acctterminatecause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctterminatecause
     *
     * @param acctterminatecause the value for radacct.acctterminatecause
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctterminatecause(String acctterminatecause) {
        this.acctterminatecause = acctterminatecause == null ? null : acctterminatecause.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.servicetype
     *
     * @return the value of radacct.servicetype
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.servicetype
     *
     * @param servicetype the value for radacct.servicetype
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype == null ? null : servicetype.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.framedprotocol
     *
     * @return the value of radacct.framedprotocol
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getFramedprotocol() {
        return framedprotocol;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.framedprotocol
     *
     * @param framedprotocol the value for radacct.framedprotocol
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setFramedprotocol(String framedprotocol) {
        this.framedprotocol = framedprotocol == null ? null : framedprotocol.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.framedipaddress
     *
     * @return the value of radacct.framedipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getFramedipaddress() {
        return framedipaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.framedipaddress
     *
     * @param framedipaddress the value for radacct.framedipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setFramedipaddress(String framedipaddress) {
        this.framedipaddress = framedipaddress == null ? null : framedipaddress.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctstartdelay
     *
     * @return the value of radacct.acctstartdelay
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Integer getAcctstartdelay() {
        return acctstartdelay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctstartdelay
     *
     * @param acctstartdelay the value for radacct.acctstartdelay
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctstartdelay(Integer acctstartdelay) {
        this.acctstartdelay = acctstartdelay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.acctstopdelay
     *
     * @return the value of radacct.acctstopdelay
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Integer getAcctstopdelay() {
        return acctstopdelay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.acctstopdelay
     *
     * @param acctstopdelay the value for radacct.acctstopdelay
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAcctstopdelay(Integer acctstopdelay) {
        this.acctstopdelay = acctstopdelay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radacct.xascendsessionsvrkey
     *
     * @return the value of radacct.xascendsessionsvrkey
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getXascendsessionsvrkey() {
        return xascendsessionsvrkey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radacct.xascendsessionsvrkey
     *
     * @param xascendsessionsvrkey the value for radacct.xascendsessionsvrkey
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setXascendsessionsvrkey(String xascendsessionsvrkey) {
        this.xascendsessionsvrkey = xascendsessionsvrkey == null ? null : xascendsessionsvrkey.trim();
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadAcct(this);
    }
}