package net.jradius.dal.model;

import com.coova.dal.Record;

public class RadGroupCheck extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupcheck.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupcheck.groupname
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String groupname = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupcheck.attribute
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String attribute = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupcheck.op
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String op = "==";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupcheck.value
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String value = "";

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupcheck.id
     *
     * @return the value of radgroupcheck.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupcheck.id
     *
     * @param id the value for radgroupcheck.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupcheck.groupname
     *
     * @return the value of radgroupcheck.groupname
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupcheck.groupname
     *
     * @param groupname the value for radgroupcheck.groupname
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupcheck.attribute
     *
     * @return the value of radgroupcheck.attribute
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupcheck.attribute
     *
     * @param attribute the value for radgroupcheck.attribute
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupcheck.op
     *
     * @return the value of radgroupcheck.op
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupcheck.op
     *
     * @param op the value for radgroupcheck.op
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupcheck.value
     *
     * @return the value of radgroupcheck.value
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupcheck.value
     *
     * @param value the value for radgroupcheck.value
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadGroupCheck(this);
    }
}