package net.jradius.dal.model;

import com.coova.dal.Record;

public class RadGroupReply extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupreply.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupreply.groupname
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String groupname = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupreply.attribute
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String attribute = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupreply.op
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String op = "=";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radgroupreply.value
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String value = "";

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupreply.id
     *
     * @return the value of radgroupreply.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupreply.id
     *
     * @param id the value for radgroupreply.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupreply.groupname
     *
     * @return the value of radgroupreply.groupname
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupreply.groupname
     *
     * @param groupname the value for radgroupreply.groupname
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupreply.attribute
     *
     * @return the value of radgroupreply.attribute
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupreply.attribute
     *
     * @param attribute the value for radgroupreply.attribute
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupreply.op
     *
     * @return the value of radgroupreply.op
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupreply.op
     *
     * @param op the value for radgroupreply.op
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radgroupreply.value
     *
     * @return the value of radgroupreply.value
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radgroupreply.value
     *
     * @param value the value for radgroupreply.value
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadGroupReply(this);
    }
}