package net.jradius.dal.model;

import com.coova.dal.Record;
import java.util.Date;

public class RadIPPool extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.pool_name
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String poolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.framedipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String framedipaddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.nasipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String nasipaddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.calledstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String calledstationid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.callingstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String callingstationid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.expiry_time
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Date expiryTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String username = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radippool.pool_key
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String poolKey;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.id
     *
     * @return the value of radippool.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.id
     *
     * @param id the value for radippool.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.pool_name
     *
     * @return the value of radippool.pool_name
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getPoolName() {
        return poolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.pool_name
     *
     * @param poolName the value for radippool.pool_name
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setPoolName(String poolName) {
        this.poolName = poolName == null ? null : poolName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.framedipaddress
     *
     * @return the value of radippool.framedipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getFramedipaddress() {
        return framedipaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.framedipaddress
     *
     * @param framedipaddress the value for radippool.framedipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setFramedipaddress(String framedipaddress) {
        this.framedipaddress = framedipaddress == null ? null : framedipaddress.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.nasipaddress
     *
     * @return the value of radippool.nasipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getNasipaddress() {
        return nasipaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.nasipaddress
     *
     * @param nasipaddress the value for radippool.nasipaddress
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setNasipaddress(String nasipaddress) {
        this.nasipaddress = nasipaddress == null ? null : nasipaddress.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.calledstationid
     *
     * @return the value of radippool.calledstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getCalledstationid() {
        return calledstationid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.calledstationid
     *
     * @param calledstationid the value for radippool.calledstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setCalledstationid(String calledstationid) {
        this.calledstationid = calledstationid == null ? null : calledstationid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.callingstationid
     *
     * @return the value of radippool.callingstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getCallingstationid() {
        return callingstationid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.callingstationid
     *
     * @param callingstationid the value for radippool.callingstationid
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setCallingstationid(String callingstationid) {
        this.callingstationid = callingstationid == null ? null : callingstationid.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.expiry_time
     *
     * @return the value of radippool.expiry_time
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Date getExpiryTime() {
        return expiryTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.expiry_time
     *
     * @param expiryTime the value for radippool.expiry_time
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setExpiryTime(Date expiryTime) {
        this.expiryTime = expiryTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.username
     *
     * @return the value of radippool.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.username
     *
     * @param username the value for radippool.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radippool.pool_key
     *
     * @return the value of radippool.pool_key
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getPoolKey() {
        return poolKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radippool.pool_key
     *
     * @param poolKey the value for radippool.pool_key
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setPoolKey(String poolKey) {
        this.poolKey = poolKey == null ? null : poolKey.trim();
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadIPPool(this);
    }
}