package net.jradius.dal.model;

import com.coova.dal.Record;
import java.util.Date;

public class RadPostAuth extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radpostauth.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radpostauth.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String username = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radpostauth.pass
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String pass = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radpostauth.reply
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private String reply = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radpostauth.authdate
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private Date authdate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radpostauth.id
     *
     * @return the value of radpostauth.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radpostauth.id
     *
     * @param id the value for radpostauth.id
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radpostauth.username
     *
     * @return the value of radpostauth.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radpostauth.username
     *
     * @param username the value for radpostauth.username
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radpostauth.pass
     *
     * @return the value of radpostauth.pass
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radpostauth.pass
     *
     * @param pass the value for radpostauth.pass
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radpostauth.reply
     *
     * @return the value of radpostauth.reply
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radpostauth.reply
     *
     * @param reply the value for radpostauth.reply
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radpostauth.authdate
     *
     * @return the value of radpostauth.authdate
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Date getAuthdate() {
        return authdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radpostauth.authdate
     *
     * @param authdate the value for radpostauth.authdate
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public void setAuthdate(Date authdate) {
        this.authdate = authdate;
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadPostAuth(this);
    }
}