package net.jradius.dal.model;

import com.coova.dal.Record;

public class RadReply extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radreply.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radreply.username
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String username = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radreply.attribute
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String attribute = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radreply.op
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String op = "=";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radreply.value
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String value = "";

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radreply.id
     *
     * @return the value of radreply.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radreply.id
     *
     * @param id the value for radreply.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radreply.username
     *
     * @return the value of radreply.username
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radreply.username
     *
     * @param username the value for radreply.username
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radreply.attribute
     *
     * @return the value of radreply.attribute
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radreply.attribute
     *
     * @param attribute the value for radreply.attribute
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radreply.op
     *
     * @return the value of radreply.op
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radreply.op
     *
     * @param op the value for radreply.op
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radreply.value
     *
     * @return the value of radreply.value
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radreply.value
     *
     * @param value the value for radreply.value
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadReply(this);
    }
}