package net.jradius.dal.model;

import com.coova.dal.Record;

public class RadUserGroup extends Record {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radusergroup.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radusergroup.username
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String username = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radusergroup.groupname
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private String groupname = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column radusergroup.priority
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private Integer priority;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radusergroup.id
     *
     * @return the value of radusergroup.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radusergroup.id
     *
     * @param id the value for radusergroup.id
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radusergroup.username
     *
     * @return the value of radusergroup.username
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radusergroup.username
     *
     * @param username the value for radusergroup.username
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radusergroup.groupname
     *
     * @return the value of radusergroup.groupname
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radusergroup.groupname
     *
     * @param groupname the value for radusergroup.groupname
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column radusergroup.priority
     *
     * @return the value of radusergroup.priority
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column radusergroup.priority
     *
     * @param priority the value for radusergroup.priority
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Record synchronizedRecord() {
        return new SynchronizedRadUserGroup(this);
    }
}