package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.NAS;
import net.jradius.dal.model.NASExample;

public interface NASDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    Long insert(NAS record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByPrimaryKey(NAS record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByPrimaryKeySelective(NAS record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    List<NAS> selectByExample(NASExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    NAS selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int deleteByExample(NASExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int countByExample(NASExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByExampleSelective(NAS record, NASExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table nas
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByExample(NAS record, NASExample example);
}