package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadAcct;
import net.jradius.dal.model.RadAcctExample;

public interface RadAcctDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(RadAcct record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(RadAcct record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(RadAcct record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<RadAcct> selectByExample(RadAcctExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    RadAcct selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(RadAcctExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(RadAcctExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(RadAcct record, RadAcctExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(RadAcct record, RadAcctExample example);
}