package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadAcct;
import net.jradius.dal.model.RadAcctExample;

public class RadAcctDAOImpl extends SqlMapClientWrapper implements RadAcctDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadAcctDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long insert(RadAcct record) {
        Object newKey = insert("radacct", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKey(RadAcct record) {
        int rows = update("radacct", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKeySelective(RadAcct record) {
        int rows = update("radacct", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<RadAcct> selectByExample(RadAcctExample example) {
        List<RadAcct> list = (List<RadAcct>) queryForList("radacct", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadAcct selectByPrimaryKey(Long id) {
        RadAcct key = new RadAcct();
        key.setId(id);
        RadAcct record = (RadAcct) queryForObject("radacct", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByExample(RadAcctExample example) {
        int rows = delete("radacct", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        RadAcct key = new RadAcct();
        key.setId(id);
        int rows = delete("radacct", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int countByExample(RadAcctExample example) {
        Integer count = (Integer)  queryForObject("radacct", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExampleSelective(RadAcct record, RadAcctExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radacct", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExample(RadAcct record, RadAcctExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radacct", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radacct
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private static class UpdateByExampleParms extends RadAcctExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadAcctExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}