package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadCheck;
import net.jradius.dal.model.RadCheckExample;

public class RadCheckDAOImpl extends SqlMapClientWrapper implements RadCheckDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadCheckDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long insert(RadCheck record) {
        Object newKey = insert("radcheck", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKey(RadCheck record) {
        int rows = update("radcheck", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKeySelective(RadCheck record) {
        int rows = update("radcheck", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<RadCheck> selectByExample(RadCheckExample example) {
        List<RadCheck> list = (List<RadCheck>) queryForList("radcheck", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadCheck selectByPrimaryKey(Long id) {
        RadCheck key = new RadCheck();
        key.setId(id);
        RadCheck record = (RadCheck) queryForObject("radcheck", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByExample(RadCheckExample example) {
        int rows = delete("radcheck", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        RadCheck key = new RadCheck();
        key.setId(id);
        int rows = delete("radcheck", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int countByExample(RadCheckExample example) {
        Integer count = (Integer)  queryForObject("radcheck", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExampleSelective(RadCheck record, RadCheckExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radcheck", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExample(RadCheck record, RadCheckExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radcheck", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private static class UpdateByExampleParms extends RadCheckExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadCheckExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}