package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadCheck;
import net.jradius.dal.model.RadCheckExample;

public interface RadCheckDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    Long insert(RadCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByPrimaryKey(RadCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByPrimaryKeySelective(RadCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    List<RadCheck> selectByExample(RadCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    RadCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int deleteByExample(RadCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int countByExample(RadCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByExampleSelective(RadCheck record, RadCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByExample(RadCheck record, RadCheckExample example);
}