package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadGroupReply;
import net.jradius.dal.model.RadGroupReplyExample;

public class RadGroupReplyDAOImpl extends SqlMapClientWrapper implements RadGroupReplyDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public RadGroupReplyDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Long insert(RadGroupReply record) {
        Object newKey = insert("radgroupreply", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByPrimaryKey(RadGroupReply record) {
        int rows = update("radgroupreply", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByPrimaryKeySelective(RadGroupReply record) {
        int rows = update("radgroupreply", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    @SuppressWarnings("unchecked")
    public List<RadGroupReply> selectByExample(RadGroupReplyExample example) {
        List<RadGroupReply> list = (List<RadGroupReply>) queryForList("radgroupreply", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public RadGroupReply selectByPrimaryKey(Long id) {
        RadGroupReply key = new RadGroupReply();
        key.setId(id);
        RadGroupReply record = (RadGroupReply) queryForObject("radgroupreply", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int deleteByExample(RadGroupReplyExample example) {
        int rows = delete("radgroupreply", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int deleteByPrimaryKey(Long id) {
        RadGroupReply key = new RadGroupReply();
        key.setId(id);
        int rows = delete("radgroupreply", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int countByExample(RadGroupReplyExample example) {
        Integer count = (Integer)  queryForObject("radgroupreply", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByExampleSelective(RadGroupReply record, RadGroupReplyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radgroupreply", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByExample(RadGroupReply record, RadGroupReplyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radgroupreply", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private static class UpdateByExampleParms extends RadGroupReplyExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadGroupReplyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}