package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadGroupCheck;
import net.jradius.dal.model.RadGroupCheckExample;

public class RadGroupCheckDAOImpl extends SqlMapClientWrapper implements RadGroupCheckDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadGroupCheckDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long insert(RadGroupCheck record) {
        Object newKey = insert("radgroupcheck", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKey(RadGroupCheck record) {
        int rows = update("radgroupcheck", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKeySelective(RadGroupCheck record) {
        int rows = update("radgroupcheck", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<RadGroupCheck> selectByExample(RadGroupCheckExample example) {
        List<RadGroupCheck> list = (List<RadGroupCheck>) queryForList("radgroupcheck", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadGroupCheck selectByPrimaryKey(Long id) {
        RadGroupCheck key = new RadGroupCheck();
        key.setId(id);
        RadGroupCheck record = (RadGroupCheck) queryForObject("radgroupcheck", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByExample(RadGroupCheckExample example) {
        int rows = delete("radgroupcheck", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        RadGroupCheck key = new RadGroupCheck();
        key.setId(id);
        int rows = delete("radgroupcheck", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int countByExample(RadGroupCheckExample example) {
        Integer count = (Integer)  queryForObject("radgroupcheck", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExampleSelective(RadGroupCheck record, RadGroupCheckExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radgroupcheck", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExample(RadGroupCheck record, RadGroupCheckExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radgroupcheck", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private static class UpdateByExampleParms extends RadGroupCheckExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadGroupCheckExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}