package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadGroupReply;
import net.jradius.dal.model.RadGroupReplyExample;

public interface RadGroupReplyDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(RadGroupReply record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(RadGroupReply record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(RadGroupReply record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<RadGroupReply> selectByExample(RadGroupReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    RadGroupReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(RadGroupReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(RadGroupReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(RadGroupReply record, RadGroupReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(RadGroupReply record, RadGroupReplyExample example);
}