package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadGroupCheck;
import net.jradius.dal.model.RadGroupCheckExample;

public interface RadGroupCheckDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(RadGroupCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(RadGroupCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(RadGroupCheck record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<RadGroupCheck> selectByExample(RadGroupCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    RadGroupCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(RadGroupCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(RadGroupCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(RadGroupCheck record, RadGroupCheckExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radgroupcheck
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(RadGroupCheck record, RadGroupCheckExample example);
}