package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadIPPool;
import net.jradius.dal.model.RadIPPoolExample;

public interface RadIPPoolDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    Long insert(RadIPPool record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByPrimaryKey(RadIPPool record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByPrimaryKeySelective(RadIPPool record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    List<RadIPPool> selectByExample(RadIPPoolExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    RadIPPool selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int deleteByExample(RadIPPoolExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int countByExample(RadIPPoolExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByExampleSelective(RadIPPool record, RadIPPoolExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    int updateByExample(RadIPPool record, RadIPPoolExample example);
}