package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadIPPool;
import net.jradius.dal.model.RadIPPoolExample;

public class RadIPPoolDAOImpl extends SqlMapClientWrapper implements RadIPPoolDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadIPPoolDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long insert(RadIPPool record) {
        Object newKey = insert("radippool", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKey(RadIPPool record) {
        int rows = update("radippool", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKeySelective(RadIPPool record) {
        int rows = update("radippool", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<RadIPPool> selectByExample(RadIPPoolExample example) {
        List<RadIPPool> list = (List<RadIPPool>) queryForList("radippool", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadIPPool selectByPrimaryKey(Long id) {
        RadIPPool key = new RadIPPool();
        key.setId(id);
        RadIPPool record = (RadIPPool) queryForObject("radippool", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByExample(RadIPPoolExample example) {
        int rows = delete("radippool", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        RadIPPool key = new RadIPPool();
        key.setId(id);
        int rows = delete("radippool", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int countByExample(RadIPPoolExample example) {
        Integer count = (Integer)  queryForObject("radippool", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExampleSelective(RadIPPool record, RadIPPoolExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radippool", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExample(RadIPPool record, RadIPPoolExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radippool", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radippool
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private static class UpdateByExampleParms extends RadIPPoolExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadIPPoolExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}