package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadPostAuth;
import net.jradius.dal.model.RadPostAuthExample;

public class RadPostAuthDAOImpl extends SqlMapClientWrapper implements RadPostAuthDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public RadPostAuthDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Long insert(RadPostAuth record) {
        Object newKey = insert("radpostauth", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByPrimaryKey(RadPostAuth record) {
        int rows = update("radpostauth", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByPrimaryKeySelective(RadPostAuth record) {
        int rows = update("radpostauth", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    @SuppressWarnings("unchecked")
    public List<RadPostAuth> selectByExample(RadPostAuthExample example) {
        List<RadPostAuth> list = (List<RadPostAuth>) queryForList("radpostauth", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public RadPostAuth selectByPrimaryKey(Long id) {
        RadPostAuth key = new RadPostAuth();
        key.setId(id);
        RadPostAuth record = (RadPostAuth) queryForObject("radpostauth", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int deleteByExample(RadPostAuthExample example) {
        int rows = delete("radpostauth", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int deleteByPrimaryKey(Long id) {
        RadPostAuth key = new RadPostAuth();
        key.setId(id);
        int rows = delete("radpostauth", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int countByExample(RadPostAuthExample example) {
        Integer count = (Integer)  queryForObject("radpostauth", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByExampleSelective(RadPostAuth record, RadPostAuthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radpostauth", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByExample(RadPostAuth record, RadPostAuthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radpostauth", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private static class UpdateByExampleParms extends RadPostAuthExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadPostAuthExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}