package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadPostAuth;
import net.jradius.dal.model.RadPostAuthExample;

public interface RadPostAuthDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(RadPostAuth record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(RadPostAuth record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(RadPostAuth record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<RadPostAuth> selectByExample(RadPostAuthExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    RadPostAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(RadPostAuthExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(RadPostAuthExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(RadPostAuth record, RadPostAuthExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radpostauth
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(RadPostAuth record, RadPostAuthExample example);
}