package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadReply;
import net.jradius.dal.model.RadReplyExample;

public interface RadReplyDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(RadReply record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(RadReply record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(RadReply record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<RadReply> selectByExample(RadReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    RadReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(RadReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(RadReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(RadReply record, RadReplyExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(RadReply record, RadReplyExample example);
}