package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadReply;
import net.jradius.dal.model.RadReplyExample;

public class RadReplyDAOImpl extends SqlMapClientWrapper implements RadReplyDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public RadReplyDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public Long insert(RadReply record) {
        Object newKey = insert("radreply", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByPrimaryKey(RadReply record) {
        int rows = update("radreply", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByPrimaryKeySelective(RadReply record) {
        int rows = update("radreply", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    @SuppressWarnings("unchecked")
    public List<RadReply> selectByExample(RadReplyExample example) {
        List<RadReply> list = (List<RadReply>) queryForList("radreply", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public RadReply selectByPrimaryKey(Long id) {
        RadReply key = new RadReply();
        key.setId(id);
        RadReply record = (RadReply) queryForObject("radreply", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int deleteByExample(RadReplyExample example) {
        int rows = delete("radreply", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int deleteByPrimaryKey(Long id) {
        RadReply key = new RadReply();
        key.setId(id);
        int rows = delete("radreply", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int countByExample(RadReplyExample example) {
        Integer count = (Integer)  queryForObject("radreply", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByExampleSelective(RadReply record, RadReplyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radreply", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    public int updateByExample(RadReply record, RadReplyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radreply", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radreply
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    private static class UpdateByExampleParms extends RadReplyExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadReplyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}