package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.RadUserGroup;
import net.jradius.dal.model.RadUserGroupExample;

public interface RadUserGroupDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(RadUserGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(RadUserGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(RadUserGroup record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<RadUserGroup> selectByExample(RadUserGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    RadUserGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(RadUserGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(RadUserGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(RadUserGroup record, RadUserGroupExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(RadUserGroup record, RadUserGroupExample example);
}