package net.jradius.dal.dao;

import com.coova.dal.SqlMapClientWrapper;
import java.util.List;
import net.jradius.dal.model.RadUserGroup;
import net.jradius.dal.model.RadUserGroupExample;

public class RadUserGroupDAOImpl extends SqlMapClientWrapper implements RadUserGroupDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadUserGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public Long insert(RadUserGroup record) {
        Object newKey = insert("radusergroup", "abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKey(RadUserGroup record) {
        int rows = update("radusergroup", "abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByPrimaryKeySelective(RadUserGroup record) {
        int rows = update("radusergroup", "abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<RadUserGroup> selectByExample(RadUserGroupExample example) {
        List<RadUserGroup> list = (List<RadUserGroup>) queryForList("radusergroup", "abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public RadUserGroup selectByPrimaryKey(Long id) {
        RadUserGroup key = new RadUserGroup();
        key.setId(id);
        RadUserGroup record = (RadUserGroup) queryForObject("radusergroup", "abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByExample(RadUserGroupExample example) {
        int rows = delete("radusergroup", "abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int deleteByPrimaryKey(Long id) {
        RadUserGroup key = new RadUserGroup();
        key.setId(id);
        int rows = delete("radusergroup", "abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int countByExample(RadUserGroupExample example) {
        Integer count = (Integer)  queryForObject("radusergroup", "abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExampleSelective(RadUserGroup record, RadUserGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radusergroup", "abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    public int updateByExample(RadUserGroup record, RadUserGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("radusergroup", "abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table radusergroup
     *
     * @abatorgenerated Mon May 04 09:56:56 CEST 2009
     */
    private static class UpdateByExampleParms extends RadUserGroupExample {
        private Object record;

        public UpdateByExampleParms(Object record, RadUserGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}