package net.jradius.dal.dao;

import java.util.List;
import net.jradius.dal.model.UIHelp;
import net.jradius.dal.model.UIHelpExample;

public interface UIHelpDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    Long insert(UIHelp record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKey(UIHelp record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByPrimaryKeySelective(UIHelp record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    List<UIHelp> selectByExample(UIHelpExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    UIHelp selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByExample(UIHelpExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int countByExample(UIHelpExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExampleSelective(UIHelp record, UIHelpExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table uihelp
     *
     * @abatorgenerated Wed Sep 10 13:54:28 CEST 2008
     */
    int updateByExample(UIHelp record, UIHelpExample example);
}